language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/hoony-app.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hoony-app-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hoony-app-build
    key: hoony-app.zip
    bundle_type: zip
    application: hoony-app
    deployment_group: hoony-app-group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jihun9838@gmail.com